<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DWK.Diagram</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Northwoods.GoDiagram.Avalonia" />
    </ItemGroup>

</Project>
