<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Avalonia" />
    </ItemGroup>
    
    <ItemGroup>
      <Reference Include="Ursa">
        <HintPath>..\..\..\..\.nuget\packages\irihi.ursa\1.6.2\lib\net8.0\Ursa.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
